/**
 * Generated by tsnapi — public API snapshot of `apifox-pull/cli`
 */
// #region Interfaces
export interface CliOptions extends ConfigValues {
  check: boolean;
  command: Command;
  config?: string;
  dryRun: boolean;
  force: boolean;
  global: boolean;
  globalConfig?: string;
  help: boolean;
  json: boolean;
}
// #endregion

// #region Functions
export declare function getHelpText(): string;
export declare function main(_?: string[]): Promise<void>;
export declare function parseCli(_: string[]): CliOptions;
export declare function runCli(_: string[], _?: Environment, _?: Writer, _?: string): Promise<void>;
// #endregion