/**
 * Generated by tsnapi — public API snapshot of `apifox-pull`
 */
// #region Functions
export declare function exportOpenApi({
  apiIds,
  baseUrl,
  check,
  dryRun,
  exportFormat,
  exportUrlTemplate,
  fetcher,
  fileNameTemplate,
  folderIds,
  onProgress,
  output,
  projectId,
  token
}: OpenApiExportOptions): Promise<OpenApiExportResult>;
export declare function getOpenApiExportUrl(_: string, _: string, _?: string): string;
export declare function getOpenApiOutputFile(_: ExportTarget, _: unknown, _?: string, _?: ExportFormat): string;
export declare function planExportTargets(_?: string[], _?: string[]): ExportTarget[];
export declare function serializeOpenApiDocument(_: unknown, _?: ExportFormat): string;
export declare function toSafeFileSegment(_: string): string;
// #endregion

// #region Variables
export declare const DEFAULT_API_VERSION: string;
export declare const DEFAULT_BASE_URL: string;
export declare const DEFAULT_EXPORT_FORMAT: "JSON";
export declare const DEFAULT_FILE_NAME_TEMPLATE: string;
export declare const DEFAULT_FILE_NAME_TEMPLATE_YAML: string;
export declare const DEFAULT_OAS_VERSION: string;
export declare const DEFAULT_OUTPUT_DIRECTORY: string;
export declare const DEFAULT_OUTPUT_FILE: string;
export declare const DEFAULT_OUTPUT_FILE_YAML: string;
// #endregion

// #region Other
export { ConfigField }
export { ConfigurationSource }
export { ConfigValues }
export { ExportFormat }
export { ExportTarget }
export { OpenApiDocument }
export { OpenApiExportOptions }
export { OpenApiExportResult }
export { ResolvedConfiguration }
// #endregion